### ISSUE TITLE
404 error when trying to PUT a new project_

### ISSUE THREAD

**Issue by Fecny** [kbsali/php-redmine-api#176]
When a trying to send a new time_entry to a Issue, it die with 404 error from the redmine.

var_dump($client->api('time_entry')->create(array(
        'issue_id' => $task_id,
        'hours' => $taskTime_format,
        'activity_id' => 5,
        'comments' => $client_note,
    )));

**Comment by ftrojahn** [comment]
Just pulled my hair about this one, too. If the $client object isn't destroyed between curl calls,
curl options aren't reset, so after e.g. a delete call, all subsequent create calls fail as
CURLOPT_CUSTOMREQUEST is set to 'DELETE'.

In a3c8846 this has been fixed, but i don't know why @kbsali hasn't done a release since then.

So, installing via composer, I get the old, unfixed behaviour. Instead, cloning this repo from github should be sufficient.

**Comment by kbsali** [comment]
sorry about that, i'll issue a new release right now.

**Comment by kbsali** [comment]
done! @Fecny & @ftrojahn could you confirm this fixed the issue?

**Comment by ftrojahn** [comment]
Yes my problem was fixed by this patch.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by kbsali** [comment]
great! Thanks @ftrojahn and sorry again about the missed release.
