### ISSUE TITLE
No author_id for create issue

### ISSUE THREAD

**Issue by rps-repo** [kbsali/php-redmine-api#221]
When creating an issue via API there is no parameter to set the author id.  At least in the 3.x branch.
Issue.php has author_id set in the defaults array.
The author will be whomever the API key belongs to that is used to create the issue.

**Comment by emilianosce** [comment]
That's right, the author will be whomever the api key belongs to. What I think you can do is using the User Impersonation method in order to create those issues.
`$client->setImpersonateUser('not_me');`
Next calls should be created (with author id) by the user 'not_me'. 
When you're done making calls with that user, you use
`$client->setImpersonateUser(null);`
Hope it works!

**Comment by kbsali** [comment]
@rps-repo I hope @emilianosce 's answer worked for you. 
I'm cleaning the list of issues (which, as you probably realized, has been abandoned :/).

I take the opportunity to let you know that I am looking for maintainers to take back this repository. If you are interested let me know.
Thanks.
