### ISSUE TITLE
All the put method returns false response with status code 200

### ISSUE THREAD

**Issue by atuljoshi** [kbsali/php-redmine-api#231]
I am updating issue with xml as follows -

`<?xml version="1.0"?>
<issue><id>310</id><subject>Testing redmine API</subject><priority_id>2</priority_id><status_id>1</status_id><tracker_id>1</tracker_id><assigned_to_id>12</assigned_to_id><due_date>2019-06-13</due_date><project_id>8</project_id><start_date>2018-10-24</start_date><created_on>2019-06-14T07:19:30Z</created_on><updated_on>2019-06-14T07:19:30Z</updated_on><estimated_hours>25</estimated_hours><done_ratio>60</done_ratio></issue>`

The issue is getting updated. The API response code is 200 but response is always false.

**Comment by atuljoshi** [comment]
I tried put method for versions as well but it is also having same response.

**Comment by Art4** [comment]
I can't test this because there are some information about the request missing. Could you please provide a code example how you call the library?

Beside that: you can always get the response status code of the last request with `$client->getLastResponseStatusCode()`. This code is the status code that comes from the Redmine server. You should use this code instead of rely on the return of a $client call.

**Comment by Art4** [comment]
This issue is inactive for a while. I hope you have found an answer to your question. I will close this issue. Feel free to reopen if you have more details.
